#!/usr/bin/env python

from re import ASCII, sub
from signal import SIGINT, signal
from subprocess import run
from sys import exit


def interrupt_handler(signal, frame):
    print('\nGoodbye')
    exit(0)


signal(SIGINT, interrupt_handler)

try:
    run(['git', '--version'], capture_output=True)
except FileNotFoundError:
    print('This script requires `git` installed into your system')
    exit(1)

print('### Welcome to the GTK Vala Template! ###\n')

app_name = input('Application name (e.g. My Awesome App): ')
app_id = input(
    'Application ID (see https://developer.gnome.org/ChooseApplicationID): ')
github_repo = input('GitHub repository: ')

# Replace any non alphanumerical character with '-'
project_name = sub('\\W+', '-', app_name.lower(), flags=ASCII)
